name: Security Scanning

on:
  pull_request:
    paths:
      - 'pipelines/dockerfiles/**'
      - 'cluster/**'

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner - IaC
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'cluster/'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'
      
      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-iac-results.sarif'
      
      - name: Run Trivy - Dockerfiles
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'pipelines/dockerfiles/'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
